# Generated by Django 4.0.5 on 2023-01-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profilepic',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
